name: Build and Push to ACR on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1 
      with:
        registry: outboundacrcicd.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: outboundacrcicd.azurecr.io/outbound/aillmprocessor:${{ github.ref_name }}

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1 
      with:
        registry: agentassistdev1.azurecr.io
        username: ${{ secrets.AA_ACR_USER }}
        password: ${{ secrets.AA_ACR_PASS }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: agentassistdev1.azurecr.io/outbound/aillmprocessor:${{ github.ref_name }}

    - name: Remove unused Docker images
      run: docker system prune -a -f