
OPENAI_API_KEY = "sk-****Uh"
MONGODB_URI = "mongodb+srv://mongo:*******@aiimageapp.lvklnwl.mongodb.net/mongodb_container?retryWrites=true&w=majority&appName=AIImageAPP"
#MONGODB_URI = "mongodb://mongo:mongo@*****:27017/mongodb_container?authSource=admin"
APP_URL = "https://hackathon-avaya-obaas.streamlit.app/"
PROCESS_DOCS = false
STORE_INDEX = false
